name: Dummy Pipeline

on:
  workflow_dispatch:
    inputs:
      variable1:
        description: 'Requestor'
        required: true
        default: 'Me@you.org'
      variable2:
        description: 'Group'
        required: true
        default: 'Users.datalake.viewers'
      variable3:
        description: 'approver'
        required: true
        default: 'john.doe@you.org'

jobs:
  print_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Print Variables
        run: |
          echo "Requestor: ${{ github.event.inputs.variable1 }}"
          echo "Group: ${{ github.event.inputs.variable2 }}"
          echo "Approver: ${{ github.event.inputs.variable3 }}"
